enableProgressBars: true

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

progressBarStyle: jack

yarnPath: .yarn/releases/yarn-3.6.3.cjs
